// 도시명 한글-영어 매핑
// questions.ts의 explanation.en에서 추출한 도시명 매핑
export const cityNameMap: Record<string, string> = {
  '시카고': 'Chicago',
  '토론토': 'Toronto',
  '뉴욕': 'New York',
  '밴쿠버': 'Vancouver',
  '로스앤젤레스': 'Los Angeles',
  '멕시코시티': 'Mexico City',
  '서울': 'Seoul',
  '부산': 'Busan',
  '도쿄': 'Tokyo',
  '오사카': 'Osaka',
  '베이징': 'Beijing',
  '상하이': 'Shanghai',
  '방콕': 'Bangkok',
  '싱가포르': 'Singapore',
  '파리': 'Paris',
  '런던': 'London',
  '베를린': 'Berlin',
  '로마': 'Rome',
  '마드리드': 'Madrid',
  '암스테르담': 'Amsterdam',
  '모스크바': 'Moscow',
  '시드니': 'Sydney',
  '멜버른': 'Melbourne',
  '리우데자네이루': 'Rio de Janeiro',
  '상파울루': 'São Paulo',
  '부에노스아이레스': 'Buenos Aires',
  '카이로': 'Cairo',
  '요하네스버그': 'Johannesburg',
  '두바이': 'Dubai',
  '델리': 'Delhi',
  '뭄바이': 'Mumbai',
  '방갈로르': 'Bangalore',
  '마닐라': 'Manila',
  '자카르타': 'Jakarta',
  '호치민': 'Ho Chi Minh City',
  '하노이': 'Hanoi',
  '쿠알라룸푸르': 'Kuala Lumpur',
  '타이페이': 'Taipei',
  '홍콩': 'Hong Kong',
  '마카오': 'Macau',
  '오타와': 'Ottawa',
  '호놀룰루': 'Honolulu',
  '몬트리올': 'Montreal',
  '보스턴': 'Boston',
  '마이애미': 'Miami',
  '에드몬턴': 'Edmonton',
  '시애틀': 'Seattle',
  '워싱턴 D.C.': 'Washington D.C.',
  '브라질리아': 'Brasília',
  '덴버': 'Denver',
  '필라델피아': 'Philadelphia',
  '퀸즈타운': 'Queenstown',
  '애틀랜타': 'Atlanta',
  '피닉스': 'Phoenix',
  '칸쿤': 'Cancún',
  '샌디에이고': 'San Diego',
  '미니애폴리스': 'Minneapolis',
  '로테르담': 'Rotterdam',
  '샌안토니오': 'San Antonio',
  '포트랜드': 'Portland',
  '케이프타운': 'Cape Town',
  '투손': 'Tucson',
  '쿠리티바': 'Curitiba',
  '리노': 'Reno',
  '바르나': 'Varna',
  '샬럿': 'Charlotte',
  '코펜하겐': 'Copenhagen',
  '뮌헨': 'Munich',
  '비엔나': 'Vienna',
  '오클랜드': 'Auckland',
  '웰링턴': 'Wellington',
  '산티아고': 'Santiago',
  '올버니': 'Albany',
  '더블린': 'Dublin',
  '프로비던스': 'Providence',
  '프라하': 'Prague',
  '데모인': 'Des Moines',
  '비스마르크': 'Bismarck',
  '샤이엔': 'Cheyenne',
  '콜럼비아': 'Columbia',
  '몽고메리': 'Montgomery',
  '오클라호마시티': 'Oklahoma City',
  '아테네': 'Athens',
  '리옹': 'Lyon',
  '바르셀로나': 'Barcelona',
  '시안': 'Xi\'an',
  '마르세유': 'Marseille',
  '제노바': 'Genoa',
  '니스': 'Nice',
  '베네치아': 'Venice',
  '나폴리': 'Naples',
  '세비야': 'Seville',
  '살바도르': 'Salvador',
  '보고타': 'Bogotá',
  '함부르크': 'Hamburg',
  '프랑크푸르트': 'Frankfurt',
  '취리히': 'Zurich',
  '브리즈번': 'Brisbane',
  '크라이스트처치': 'Christchurch',
  '퍼스': 'Perth',
  '수바': 'Suva',
  '요코하마': 'Yokohama',
  '교토': 'Kyoto',
  '광저우': 'Guangzhou',
  '선전': 'Shenzhen',
  '툴루즈': 'Toulouse',
  '발렌시아': 'Valencia',
  '보르도': 'Bordeaux',
  '포르토': 'Porto',
  '피렌체': 'Florence',
  '그라나다': 'Granada',
  '팔레르모': 'Palermo',
  '포르투알레그리': 'Porto Alegre',
  '몬테비데오': 'Montevideo',
  '레시페': 'Recife',
  '라파스': 'La Paz',
  '쾰른': 'Cologne',
  '브뤼셀': 'Brussels',
  '드레스덴': 'Dresden',
  '애들레이드': 'Adelaide',
  '다윈': 'Darwin',
  '포트모르즈비': 'Port Moresby',
  '고베': 'Kobe',
  '인천': 'Incheon',
  '후쿠오카': 'Fukuoka',
  '청두': 'Chengdu',
};

// 도시명을 언어에 따라 변환
export function getCityName(cityKo: string, language: 'ko' | 'en'): string {
  if (language === 'ko') {
    return cityKo;
  }
  return cityNameMap[cityKo] || cityKo;
}

